export const affectedOrgansLabels: Record<string, string> = {
  spleen: "Bazo",
  kidney_right: "Riñón derecho",
  kidney_left: "Riñón izquierdo",
  gallbladder: "Vesícula biliar",
  liver: "Hígado",
  stomach: "Estómago",
  pancreas: "Páncreas",
  adrenal_gland_right: "Glándula suprarrenal derecha",
  adrenal_gland_left: "Glándula suprarrenal izquierda",
  lung_upper_lobe_left: "Lóbulo superior del pulmón izquierdo",
  lung_lower_lobe_left: "Lóbulo inferior del pulmón izquierdo",
  lung_upper_lobe_right: "Lóbulo superior del pulmón derecho",
  lung_middle_lobe_right: "Lóbulo medio del pulmón derecho",
  lung_lower_lobe_right: "Lóbulo inferior del pulmón derecho",
  esophagus: "Esófago",
  trachea: "Tráquea",
  thyroid_gland: "Glándula tiroides",
  small_bowel: "Intestino delgado",
  duodenum: "Duodeno",
  colon: "Colon",
  urinary_bladder: "Vejiga urinaria",
  prostate: "Próstata",
  kidney_cyst_left: "Quiste renal izquierdo",
  kidney_cyst_right: "Quiste renal derecho",
  sacrum: "Sacro",
  vertebrae_S1: "Vértebra S1",
  vertebrae_L5: "Vértebra L5",
  vertebrae_L4: "Vértebra L4",
  vertebrae_L3: "Vértebra L3",
  vertebrae_L2: "Vértebra L2",
  vertebrae_L1: "Vértebra L1",
  vertebrae_T12: "Vértebra T12",
  vertebrae_T11: "Vértebra T11",
  vertebrae_T10: "Vértebra T10",
  vertebrae_T9: "Vértebra T9",
  vertebrae_T8: "Vértebra T8",
  vertebrae_T7: "Vértebra T7",
  vertebrae_T6: "Vértebra T6",
  vertebrae_T5: "Vértebra T5",
  vertebrae_T4: "Vértebra T4",
  vertebrae_T3: "Vértebra T3",
  vertebrae_T2: "Vértebra T2",
  vertebrae_T1: "Vértebra T1",
  vertebrae_C7: "Vértebra C7",
  vertebrae_C6: "Vértebra C6",
  vertebrae_C5: "Vértebra C5",
  vertebrae_C4: "Vértebra C4",
  vertebrae_C3: "Vértebra C3",
  vertebrae_C2: "Vértebra C2",
  vertebrae_C1: "Vértebra C1",
  heart: "Corazón",
  aorta: "Aorta",
  pulmonary_vein: "Vena pulmonar",
  brachiocephalic_trunk: "Tronco braquiocefálico",
  subclavian_artery_right: "Arteria subclavia derecha",
  subclavian_artery_left: "Arteria subclavia izquierda",
  common_carotid_artery_right: "Arteria carótida común derecha",
  common_carotid_artery_left: "Arteria carótida común izquierda",
  brachiocephalic_vein_left: "Vena braquiocefálica izquierda",
  brachiocephalic_vein_right: "Vena braquiocefálica derecha",
  atrial_appendage_left: "Apéndice auricular izquierdo",
  superior_vena_cava: "Vena cava superior",
  inferior_vena_cava: "Vena cava inferior",
  portal_vein_and_splenic_vein: "Vena porta hepática",
  iliac_artery_left: "Arteria ilíaca común izquierda",
  iliac_artery_right: "Arteria ilíaca común derecha",
  iliac_vena_left: "Vena ilíaca común izquierda",
  iliac_vena_right: "Vena ilíaca común derecha",
  humerus_left: "Húmero izquierdo",
  humerus_right: "Húmero derecho",
  scapula_left: "Escápula izquierda",
  scapula_right: "Escápula derecha",
  clavicula_left: "Clavícula izquierda",
  clavicula_right: "Clavícula derecha",
  femur_left: "Fémur izquierdo",
  femur_right: "Fémur derecho",
  hip_left: "Cadera izquierda",
  hip_right: "Cadera derecha",
  spinal_cord: "Médula espinal",
  gluteus_maximus_left: "Glúteo mayor izquierdo",
  gluteus_maximus_right: "Glúteo mayor derecho",
  gluteus_medius_left: "Glúteo medio izquierdo",
  gluteus_medius_right: "Glúteo medio derecho",
  gluteus_minimus_left: "Glúteo menor izquierdo",
  gluteus_minimus_right: "Glúteo menor derecho",
  autochthon_left: "Autóctono izquierdo",
  autochthon_right: "Autóctono derecho",
  iliopsoas_left: "Psoas ilíaco izquierdo",
  iliopsoas_right: "Psoas ilíaco derecho",
  brain: "Cerebro",
  skull: "Cráneo",
  rib_left_1: "Costilla izquierda 1",
  rib_left_2: "Costilla izquierda 2",
  rib_left_3: "Costilla izquierda 3",
  rib_left_4: "Costilla izquierda 4",
  rib_left_5: "Costilla izquierda 5",
  rib_left_6: "Costilla izquierda 6",
  rib_left_7: "Costilla izquierda 7",
  rib_left_8: "Costilla izquierda 8",
  rib_left_9: "Costilla izquierda 9",
  rib_left_10: "Costilla izquierda 10",
  rib_left_11: "Costilla izquierda 11",
  rib_left_12: "Costilla izquierda 12",
  rib_right_1: "Costilla derecha 1",
  rib_right_2: "Costilla derecha 2",
  rib_right_3: "Costilla derecha 3",
  rib_right_4: "Costilla derecha 4",
  rib_right_5: "Costilla derecha 5",
  rib_right_6: "Costilla derecha 6",
  rib_right_7: "Costilla derecha 7",
  rib_right_8: "Costilla derecha 8",
  rib_right_9: "Costilla derecha 9",
  rib_right_10: "Costilla derecha 10",
  rib_right_11: "Costilla derecha 11",
  rib_right_12: "Costilla derecha 12",
  sternum: "Esternón",
  costal_cartilages: "Cartílagos costales",

  // Missing labels:
  heart_myocardium: "Miocardio",
  heart_atrium_left: "Aurícula izquierda",
  heart_ventricle_left: "Ventrículo izquierdo",
  heart_atrium_right: "Aurícula derecha",
  heart_ventricle_right: "Ventrículo derecho",
  pulmonary_artery: "Arteria pulmonar",
  unknown: "Desconocido",
};
